/* The following code was generated by JFlex 1.4.3 on 6/11/24, 1:34 */

// * Archivo de especificación léxica *
package com.compi;

import java_cup.runtime.Symbol;
import TokenTable.TokenInfo; // Importar TokenInfo para manejo de información de tokens
import java.util.ArrayList;
import java_cup.runtime.Scanner;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/11/24, 1:34 from the specification file
 * <tt>C:/Users/DEVAN/Documents/2024/Segundo semestre/Compi/Proyecto 2/Revisión previa previa 2/Testeo prueba/src/main/java/com/compi/simple.flex</tt>
 */
public class DemoLexer implements java_cup.runtime.Scanner {

  @Override
  public Symbol next_token() throws java.io.IOException {
    // Llama a yylex() y devuelve el símbolo léxico generado
    return yylex();
  }

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\2\0\1\3\22\0\1\3\1\50\1\64\2\0"+
    "\1\62\1\61\1\65\1\7\1\15\1\16\1\14\1\55\1\51\1\66"+
    "\1\5\1\70\7\1\2\1\1\56\1\54\1\60\1\47\1\57\2\0"+
    "\4\72\1\67\1\72\21\2\1\71\2\2\1\10\1\6\1\12\1\11"+
    "\2\0\1\25\1\35\1\26\1\34\1\32\1\22\1\37\1\27\1\17"+
    "\1\2\1\40\1\23\1\41\1\20\1\24\1\45\1\2\1\30\1\36"+
    "\1\21\1\33\1\46\1\31\1\42\1\44\1\43\1\52\1\13\1\53"+
    "\1\63\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\17\3\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\1\1\2\1\0\1\3"+
    "\1\0\1\33\1\0\1\34\1\35\1\36\1\37\1\40"+
    "\1\3\1\41\16\3\1\42\10\3\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\0"+
    "\1\55\2\0\1\56\1\0\1\2\1\57\1\60\1\0"+
    "\1\61\1\62\2\3\1\63\31\3\1\64\1\65\1\66"+
    "\1\57\1\0\2\3\1\67\1\70\2\3\1\71\1\72"+
    "\3\3\1\73\1\74\14\3\1\75\1\76\1\3\1\77"+
    "\2\0\1\3\1\100\1\3\1\101\2\3\1\102\1\3"+
    "\1\103\3\3\1\104\4\3\1\105\2\3\1\0\2\3"+
    "\1\106\1\3\1\107\1\3\1\110\1\3\1\111\1\112"+
    "\1\113\1\114\1\115\1\3\1\0\1\116\3\3\1\117"+
    "\1\3\1\0\1\120\1\121\1\122\1\123\10\0\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\73\0\u0127\0\73"+
    "\0\73\0\u0162\0\u019d\0\73\0\u01d8\0\u0213\0\u024e\0\u0289"+
    "\0\u02c4\0\u02ff\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461"+
    "\0\u049c\0\u04d7\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\73"+
    "\0\73\0\73\0\73\0\73\0\u0639\0\u0674\0\u06af\0\u06ea"+
    "\0\73\0\u0725\0\u0760\0\u079b\0\u07d6\0\u0811\0\u084c\0\u0887"+
    "\0\u08c2\0\73\0\73\0\73\0\73\0\73\0\u08fd\0\u0811"+
    "\0\u0938\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5"+
    "\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0cad"+
    "\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\73"+
    "\0\73\0\73\0\73\0\73\0\73\0\73\0\73\0\73"+
    "\0\73\0\u0e85\0\73\0\u0ec0\0\u0efb\0\73\0\u0f36\0\u0f71"+
    "\0\73\0\u0fac\0\u0fe7\0\73\0\u0811\0\u1022\0\u105d\0\u0811"+
    "\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf\0\u11fa\0\u1235"+
    "\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397\0\u13d2\0\u140d"+
    "\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5"+
    "\0\u1620\0\73\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747\0\u1782"+
    "\0\u0811\0\u0811\0\u17bd\0\u17f8\0\u0811\0\u0811\0\u1833\0\u186e"+
    "\0\u18a9\0\u0811\0\u0811\0\u18e4\0\u191f\0\u195a\0\u1995\0\u19d0"+
    "\0\u1a0b\0\u1a46\0\u1a81\0\u1abc\0\u1af7\0\u1b32\0\u1b6d\0\u0811"+
    "\0\u0811\0\u1ba8\0\u1be3\0\u1be3\0\u1c1e\0\u1c59\0\u0811\0\u1c94"+
    "\0\u0811\0\u1ccf\0\u1d0a\0\u0811\0\u1d45\0\u0811\0\u1d80\0\u1dbb"+
    "\0\u1df6\0\u0811\0\u1e31\0\u1e6c\0\u1ea7\0\u1ee2\0\u0811\0\u1f1d"+
    "\0\u1f58\0\u1f93\0\u1fce\0\u2009\0\u0811\0\u2044\0\u0811\0\u207f"+
    "\0\u0811\0\u20ba\0\u0811\0\u0811\0\u0811\0\u0811\0\u0811\0\u20f5"+
    "\0\u2130\0\u0811\0\u216b\0\u21a6\0\u21e1\0\u0811\0\u221c\0\u2257"+
    "\0\u0811\0\u0811\0\u0811\0\u0811\0\u2292\0\u22cd\0\u2308\0\u2343"+
    "\0\u237e\0\u23b9\0\u23f4\0\u242f\0\73";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\2\1\11\1\2\1\12\1\13\1\14\1\15\1\16"+
    "\1\4\1\17\1\20\1\21\1\4\1\22\1\23\1\4"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\6\4\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\2\1\4\1\54\2\4\74\0\1\3\64\0"+
    "\1\55\1\0\1\3\3\0\2\56\1\57\13\0\30\56"+
    "\20\0\4\56\3\0\1\5\74\0\1\60\1\61\40\0"+
    "\1\62\36\0\1\63\73\0\1\64\32\0\1\65\72\0"+
    "\1\66\24\0\2\56\1\57\13\0\1\56\1\67\1\56"+
    "\1\70\24\56\20\0\4\56\1\0\2\56\1\57\13\0"+
    "\25\56\1\71\2\56\20\0\4\56\1\0\2\56\1\57"+
    "\13\0\4\56\1\72\1\73\22\56\20\0\4\56\1\0"+
    "\2\56\1\57\13\0\5\56\1\74\22\56\20\0\4\56"+
    "\1\0\2\56\1\57\13\0\14\56\1\75\13\56\20\0"+
    "\4\56\1\0\2\56\1\57\13\0\5\56\1\76\1\77"+
    "\1\56\1\100\17\56\20\0\4\56\1\0\2\56\1\57"+
    "\13\0\13\56\1\101\14\56\20\0\4\56\1\0\2\56"+
    "\1\57\13\0\10\56\1\102\17\56\20\0\4\56\1\0"+
    "\2\56\1\57\13\0\1\56\1\103\2\56\1\104\16\56"+
    "\1\105\4\56\20\0\4\56\1\0\2\56\1\57\13\0"+
    "\1\56\1\106\26\56\20\0\4\56\1\0\2\56\1\57"+
    "\13\0\5\56\1\107\5\56\1\110\14\56\20\0\4\56"+
    "\1\0\2\56\1\57\13\0\11\56\1\111\16\56\20\0"+
    "\4\56\1\0\2\56\1\57\13\0\1\112\1\56\1\113"+
    "\5\56\1\114\1\56\1\115\15\56\20\0\4\56\1\0"+
    "\2\56\1\57\13\0\5\56\1\116\22\56\20\0\4\56"+
    "\1\0\2\56\1\57\13\0\5\56\1\117\22\56\20\0"+
    "\4\56\47\0\1\120\72\0\1\121\72\0\1\122\1\0"+
    "\1\123\70\0\1\124\7\0\1\125\62\0\1\126\10\0"+
    "\1\127\73\0\1\130\60\0\1\131\23\0\6\52\1\132"+
    "\55\52\1\133\6\52\6\134\1\135\56\134\1\136\5\134"+
    "\1\0\1\3\40\0\1\137\23\0\1\55\1\0\1\3"+
    "\1\137\2\0\1\140\30\0\1\141\34\0\1\141\1\140"+
    "\3\0\2\56\14\0\30\56\20\0\4\56\1\0\2\142"+
    "\1\57\13\0\30\142\20\0\4\142\4\60\1\0\66\60"+
    "\7\0\1\143\6\0\1\144\55\0\2\56\14\0\2\56"+
    "\1\145\25\56\20\0\4\56\1\0\2\56\14\0\26\56"+
    "\1\146\1\56\20\0\4\56\1\0\2\56\14\0\5\56"+
    "\1\147\22\56\20\0\4\56\1\0\2\56\14\0\11\56"+
    "\1\150\16\56\20\0\4\56\1\0\2\56\14\0\1\56"+
    "\1\151\26\56\20\0\4\56\1\0\2\56\14\0\2\56"+
    "\1\152\25\56\20\0\4\56\1\0\2\56\14\0\1\56"+
    "\1\153\26\56\20\0\4\56\1\0\2\56\14\0\17\56"+
    "\1\154\10\56\20\0\4\56\1\0\2\56\14\0\6\56"+
    "\1\155\21\56\20\0\4\56\1\0\2\56\14\0\2\56"+
    "\1\156\15\56\1\157\7\56\20\0\4\56\1\0\2\56"+
    "\14\0\1\160\27\56\20\0\4\56\1\0\2\56\14\0"+
    "\14\56\1\161\13\56\20\0\4\56\1\0\2\56\14\0"+
    "\17\56\1\162\10\56\20\0\4\56\1\0\2\56\14\0"+
    "\2\56\1\163\25\56\20\0\4\56\1\0\2\56\14\0"+
    "\1\164\16\56\1\165\10\56\20\0\4\56\1\0\2\56"+
    "\14\0\14\56\1\166\13\56\20\0\4\56\1\0\2\56"+
    "\14\0\3\56\1\167\24\56\20\0\4\56\1\0\2\56"+
    "\14\0\13\56\1\170\14\56\20\0\4\56\1\0\2\56"+
    "\14\0\20\56\1\171\3\56\1\172\3\56\20\0\4\56"+
    "\1\0\2\56\14\0\6\56\1\173\2\56\1\174\16\56"+
    "\20\0\4\56\1\0\2\56\14\0\5\56\1\175\22\56"+
    "\20\0\4\56\1\0\2\56\14\0\1\176\27\56\20\0"+
    "\4\56\1\0\2\56\14\0\2\56\1\177\25\56\20\0"+
    "\4\56\1\0\2\56\14\0\1\200\3\56\1\201\23\56"+
    "\20\0\4\56\4\52\1\0\66\52\65\0\1\202\5\0"+
    "\4\134\1\0\66\134\1\203\1\204\20\203\1\204\2\203"+
    "\2\204\3\203\1\204\1\203\2\204\31\203\2\204\1\203"+
    "\1\204\1\0\1\140\30\0\1\205\34\0\1\205\1\140"+
    "\5\0\1\57\77\0\1\206\63\0\2\56\14\0\13\56"+
    "\1\207\14\56\20\0\4\56\1\0\2\56\14\0\6\56"+
    "\1\210\21\56\20\0\4\56\1\0\2\56\14\0\20\56"+
    "\1\211\7\56\20\0\4\56\1\0\2\56\14\0\5\56"+
    "\1\212\22\56\20\0\4\56\1\0\2\56\14\0\2\56"+
    "\1\213\14\56\1\214\10\56\20\0\4\56\1\0\2\56"+
    "\14\0\13\56\1\215\14\56\20\0\4\56\1\0\2\56"+
    "\14\0\11\56\1\216\16\56\20\0\4\56\1\0\2\56"+
    "\14\0\14\56\1\217\13\56\20\0\4\56\1\0\2\56"+
    "\14\0\1\220\27\56\20\0\4\56\1\0\2\56\14\0"+
    "\4\56\1\221\23\56\20\0\4\56\1\0\2\56\14\0"+
    "\22\56\1\222\5\56\20\0\4\56\1\0\2\56\14\0"+
    "\13\56\1\223\14\56\20\0\4\56\1\0\2\56\14\0"+
    "\13\56\1\224\14\56\20\0\4\56\1\0\2\56\14\0"+
    "\5\56\1\225\22\56\20\0\4\56\1\0\2\56\14\0"+
    "\1\226\27\56\20\0\4\56\1\0\2\56\14\0\16\56"+
    "\1\227\11\56\20\0\4\56\1\0\2\56\14\0\6\56"+
    "\1\230\21\56\20\0\4\56\1\0\2\56\14\0\6\56"+
    "\1\231\21\56\20\0\4\56\1\0\2\56\14\0\1\56"+
    "\1\232\26\56\20\0\4\56\1\0\2\56\14\0\13\56"+
    "\1\233\14\56\20\0\4\56\1\0\2\56\14\0\2\56"+
    "\1\234\25\56\20\0\4\56\1\0\2\56\14\0\14\56"+
    "\1\235\13\56\20\0\4\56\1\0\2\56\14\0\11\56"+
    "\1\236\16\56\20\0\4\56\1\0\2\56\14\0\2\56"+
    "\1\237\25\56\20\0\4\56\1\0\2\56\14\0\5\56"+
    "\1\240\22\56\20\0\4\56\1\0\2\56\14\0\15\56"+
    "\1\241\12\56\20\0\4\56\1\0\2\56\14\0\6\56"+
    "\1\242\21\56\20\0\4\56\1\203\1\0\20\203\1\0"+
    "\2\203\2\0\3\203\1\0\1\203\2\0\31\203\2\0"+
    "\1\203\2\0\1\204\20\0\1\204\2\0\2\204\3\0"+
    "\1\204\1\0\2\204\31\0\2\204\1\0\1\204\1\0"+
    "\1\243\12\0\1\244\34\0\1\244\16\0\1\243\13\0"+
    "\1\245\62\0\2\56\14\0\15\56\1\246\12\56\20\0"+
    "\4\56\1\0\2\56\14\0\2\56\1\247\25\56\20\0"+
    "\4\56\1\0\2\56\14\0\1\250\27\56\20\0\4\56"+
    "\1\0\2\56\14\0\2\56\1\251\25\56\20\0\4\56"+
    "\1\0\2\56\14\0\11\56\1\252\16\56\20\0\4\56"+
    "\1\0\2\56\14\0\17\56\1\253\10\56\20\0\4\56"+
    "\1\0\2\56\14\0\13\56\1\254\14\56\20\0\4\56"+
    "\1\0\2\56\14\0\11\56\1\255\16\56\20\0\4\56"+
    "\1\0\2\56\14\0\1\56\1\256\26\56\20\0\4\56"+
    "\1\0\2\56\14\0\20\56\1\257\7\56\20\0\4\56"+
    "\1\0\2\56\14\0\4\56\1\260\23\56\20\0\4\56"+
    "\1\0\2\56\14\0\14\56\1\261\13\56\20\0\4\56"+
    "\1\0\2\56\14\0\21\56\1\262\6\56\20\0\4\56"+
    "\1\0\2\56\14\0\13\56\1\263\14\56\20\0\4\56"+
    "\1\0\2\56\14\0\5\56\1\264\22\56\20\0\4\56"+
    "\1\0\2\56\14\0\1\265\27\56\20\0\4\56\1\0"+
    "\2\56\14\0\7\56\1\266\20\56\20\0\4\56\1\0"+
    "\2\56\14\0\2\56\1\267\25\56\20\0\4\56\1\0"+
    "\2\56\14\0\7\56\1\270\20\56\20\0\4\56\1\0"+
    "\2\56\14\0\2\56\1\271\25\56\20\0\4\56\1\0"+
    "\1\243\66\0\1\243\14\0\1\272\61\0\2\56\14\0"+
    "\13\56\1\273\14\56\20\0\4\56\1\0\2\56\14\0"+
    "\1\56\1\274\26\56\20\0\4\56\1\0\2\56\14\0"+
    "\1\56\1\275\26\56\20\0\4\56\1\0\2\56\14\0"+
    "\2\56\1\276\25\56\20\0\4\56\1\0\2\56\14\0"+
    "\1\56\1\277\26\56\20\0\4\56\1\0\2\56\14\0"+
    "\1\56\1\300\26\56\20\0\4\56\1\0\2\56\14\0"+
    "\13\56\1\301\14\56\20\0\4\56\1\0\2\56\14\0"+
    "\4\56\1\302\23\56\20\0\4\56\1\0\2\56\14\0"+
    "\15\56\1\303\12\56\20\0\4\56\1\0\2\56\14\0"+
    "\3\56\1\304\24\56\20\0\4\56\1\0\2\56\14\0"+
    "\7\56\1\305\20\56\20\0\4\56\1\0\2\56\14\0"+
    "\2\56\1\306\25\56\20\0\4\56\1\0\2\56\14\0"+
    "\10\56\1\307\17\56\20\0\4\56\1\0\2\56\14\0"+
    "\1\310\27\56\20\0\4\56\13\0\1\311\60\0\2\56"+
    "\14\0\3\56\1\312\24\56\20\0\4\56\1\0\2\56"+
    "\14\0\14\56\1\313\13\56\20\0\4\56\1\0\2\56"+
    "\14\0\13\56\1\314\14\56\20\0\4\56\1\0\2\56"+
    "\14\0\13\56\1\315\14\56\20\0\4\56\1\0\2\56"+
    "\14\0\2\56\1\316\25\56\20\0\4\56\1\0\2\56"+
    "\14\0\4\56\1\317\23\56\20\0\4\56\6\0\1\320"+
    "\65\0\2\56\14\0\13\56\1\321\14\56\20\0\4\56"+
    "\1\0\2\56\14\0\11\56\1\322\16\56\20\0\4\56"+
    "\1\0\2\56\14\0\15\56\1\323\12\56\20\0\4\56"+
    "\1\0\2\56\14\0\13\56\1\324\14\56\20\0\4\56"+
    "\14\0\1\325\66\0\1\326\73\0\1\327\66\0\1\330"+
    "\77\0\1\331\75\0\1\332\63\0\1\333\100\0\1\334"+
    "\63\0\1\335\65\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9322];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\2\11\2\1\1\11"+
    "\23\1\5\11\4\1\1\11\3\1\1\0\1\1\1\0"+
    "\1\1\1\0\5\11\31\1\12\11\1\0\1\11\2\0"+
    "\1\11\1\0\1\1\1\11\1\1\1\0\1\11\35\1"+
    "\1\11\3\1\1\0\35\1\2\0\24\1\1\0\16\1"+
    "\1\0\6\1\1\0\4\1\10\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private ArrayList<String> lexicalErrors = new ArrayList<>();
    private int lineNumber = 1;

    // Método para acceder a los errores léxicos
    public ArrayList<String> getLexicalErrors() {
        return lexicalErrors;
    }

    // Método para incrementar el número de línea
    private void incrementLineNumber() {
        lineNumber++;
    }

    private TokenInfo createTokenInfo(String lexeme) {
        return new TokenInfo((lexeme != null) ? lexeme : "", lineNumber, yycolumn); // Manejo de valores nulos en lexeme
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public DemoLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public DemoLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 33: 
          { return new Symbol(sym.IF, createTokenInfo(yytext()));
          }
        case 84: break;
        case 22: 
          { return new Symbol(sym.MENOR, createTokenInfo(yytext()));
          }
        case 85: break;
        case 46: 
          { lexicalErrors.add("Error: Carácter mal formado en línea " + lineNumber); return new Symbol(sym.ERROR, createTokenInfo(yytext()));
          }
        case 86: break;
        case 62: 
          { return new Symbol(sym.VOID, createTokenInfo(yytext()));
          }
        case 87: break;
        case 56: 
          { return new Symbol(sym.AUTO, createTokenInfo(yytext()));
          }
        case 88: break;
        case 51: 
          { return new Symbol(sym.FOR, createTokenInfo(yytext()));
          }
        case 89: break;
        case 19: 
          { return new Symbol(sym.COMA, createTokenInfo(yytext()));
          }
        case 90: break;
        case 68: 
          { return new Symbol(sym.BREAK, createTokenInfo(yytext()));
          }
        case 91: break;
        case 66: 
          { return new Symbol(sym.WHILE, createTokenInfo(yytext()));
          }
        case 92: break;
        case 53: 
          { lexicalErrors.add("Error: Número hexadecimal mal formado en línea " + lineNumber); return new Symbol(sym.ERROR, createTokenInfo(yytext()));
          }
        case 93: break;
        case 17: 
          { return new Symbol(sym.LLAVE_DER, createTokenInfo(yytext()));
          }
        case 94: break;
        case 24: 
          { return new Symbol(sym.MODULO, createTokenInfo(yytext()));
          }
        case 95: break;
        case 59: 
          { return new Symbol(sym.ENUM, createTokenInfo(yytext()));
          }
        case 96: break;
        case 38: 
          { return new Symbol(sym.DECREMENTO, createTokenInfo(yytext()));
          }
        case 97: break;
        case 65: 
          { return new Symbol(sym.CONST, createTokenInfo(yytext()));
          }
        case 98: break;
        case 81: 
          { return new Symbol(sym.REGISTER, createTokenInfo(yytext()));
          }
        case 99: break;
        case 14: 
          { return new Symbol(sym.NOT_LOGICO, createTokenInfo(yytext()));
          }
        case 100: break;
        case 64: 
          { return new Symbol(sym.FLOAT, createTokenInfo(yytext()));
          }
        case 101: break;
        case 25: 
          { return new Symbol(sym.COMPLEMENTO_BINARIO, createTokenInfo(yytext()));
          }
        case 102: break;
        case 40: 
          { return new Symbol(sym.DESPLAZAMIENTO_DER, createTokenInfo(yytext()));
          }
        case 103: break;
        case 5: 
          { incrementLineNumber(); return new Symbol(sym.NEWLINE, createTokenInfo(yytext()));
          }
        case 104: break;
        case 55: 
          { return new Symbol(sym.LONG, createTokenInfo(yytext()));
          }
        case 105: break;
        case 20: 
          { return new Symbol(sym.COLON, createTokenInfo(yytext()));
          }
        case 106: break;
        case 73: 
          { return new Symbol(sym.SIGNED, createTokenInfo(yytext()));
          }
        case 107: break;
        case 2: 
          { return new Symbol(sym.NUM, createTokenInfo(yytext()));
          }
        case 108: break;
        case 13: 
          { return new Symbol(sym.ASIGNACION, createTokenInfo(yytext()));
          }
        case 109: break;
        case 1: 
          { lexicalErrors.add("Error léxico en línea " + lineNumber + ": símbolo no reconocido '" + yytext() + "'");
    return new Symbol(sym.ERROR, createTokenInfo(yytext()));
          }
        case 110: break;
        case 32: 
          { return new Symbol(sym.ASIGNACION_MULTIPLICATIVA, createTokenInfo(yytext()));
          }
        case 111: break;
        case 83: 
          { return new Symbol(sym.VOLATILE, createTokenInfo(yytext()));
          }
        case 112: break;
        case 26: 
          { lexicalErrors.add("Error: Cadena sin cerrar en línea " + lineNumber); return new Symbol(sym.ERROR, createTokenInfo(yytext()));
          }
        case 113: break;
        case 71: 
          { return new Symbol(sym.EXTERN, createTokenInfo(yytext()));
          }
        case 114: break;
        case 74: 
          { return new Symbol(sym.SIZEOF, createTokenInfo(yytext()));
          }
        case 115: break;
        case 58: 
          { return new Symbol(sym.CHAR, createTokenInfo(yytext()));
          }
        case 116: break;
        case 37: 
          { return new Symbol(sym.ASIGNACION_SUSTRACTIVA, createTokenInfo(yytext()));
          }
        case 117: break;
        case 36: 
          { return new Symbol(sym.NO_IGUAL, createTokenInfo(yytext()));
          }
        case 118: break;
        case 21: 
          { return new Symbol(sym.MAYOR, createTokenInfo(yytext()));
          }
        case 119: break;
        case 7: 
          { return new Symbol(sym.PARENTESIS_IZQ, createTokenInfo(yytext()));
          }
        case 120: break;
        case 75: 
          { return new Symbol(sym.STATIC, createTokenInfo(yytext()));
          }
        case 121: break;
        case 45: 
          { return new Symbol(sym.STRING, createTokenInfo(yytext()));
          }
        case 122: break;
        case 50: 
          { return new Symbol(sym.INT, createTokenInfo(yytext()));
          }
        case 123: break;
        case 79: 
          { return new Symbol(sym.DEFAULT, createTokenInfo(yytext()));
          }
        case 124: break;
        case 80: 
          { return new Symbol(sym.CONTINUE, createTokenInfo(yytext()));
          }
        case 125: break;
        case 3: 
          { return new Symbol(sym.ID, createTokenInfo(yytext()));
          }
        case 126: break;
        case 43: 
          { return new Symbol(sym.AND_LOGICO, createTokenInfo(yytext()));
          }
        case 127: break;
        case 72: 
          { return new Symbol(sym.DOUBLE, createTokenInfo(yytext()));
          }
        case 128: break;
        case 67: 
          { return new Symbol(sym.UNION, createTokenInfo(yytext()));
          }
        case 129: break;
        case 82: 
          { return new Symbol(sym.UNSIGNED, createTokenInfo(yytext()));
          }
        case 130: break;
        case 41: 
          { return new Symbol(sym.MENOR_IGUAL, createTokenInfo(yytext()));
          }
        case 131: break;
        case 78: 
          { return new Symbol(sym.TYPEDEF, createTokenInfo(yytext()));
          }
        case 132: break;
        case 8: 
          { return new Symbol(sym.XOR_BINARIO, createTokenInfo(yytext()));
          }
        case 133: break;
        case 77: 
          { return new Symbol(sym.SWITCH, createTokenInfo(yytext()));
          }
        case 134: break;
        case 39: 
          { return new Symbol(sym.MAYOR_IGUAL, createTokenInfo(yytext()));
          }
        case 135: break;
        case 76: 
          { return new Symbol(sym.STRUCT, createTokenInfo(yytext()));
          }
        case 136: break;
        case 52: 
          { return new Symbol(sym.CHAR_LITERAL, createTokenInfo(yytext()));
          }
        case 137: break;
        case 35: 
          { return new Symbol(sym.IGUALDAD, createTokenInfo(yytext()));
          }
        case 138: break;
        case 10: 
          { return new Symbol(sym.ADITIVO, createTokenInfo(yytext()));
          }
        case 139: break;
        case 47: 
          { lexicalErrors.add("Error: Número científico mal formado en línea " + lineNumber); return new Symbol(sym.ERROR, createTokenInfo(yytext()));
          }
        case 140: break;
        case 9: 
          { return new Symbol(sym.OR_BINARIO, createTokenInfo(yytext()));
          }
        case 141: break;
        case 6: 
          { return new Symbol(sym.DIVISION, createTokenInfo(yytext()));
          }
        case 142: break;
        case 49: 
          { lexicalErrors.add("Error: Comentario sin terminar en línea " + lineNumber);
    return new Symbol(sym.ERROR, createTokenInfo(yytext()));
          }
        case 143: break;
        case 54: 
          { return new Symbol(sym.NUM_HEX, createTokenInfo(yytext()));
          }
        case 144: break;
        case 48: 
          { lexicalErrors.add("Error: Identificador mal formado con espacios en línea " + lineNumber);
    return new Symbol(sym.ERROR, createTokenInfo(yytext()));
          }
        case 145: break;
        case 15: 
          { return new Symbol(sym.SUSTRACTIVO, createTokenInfo(yytext()));
          }
        case 146: break;
        case 30: 
          { return new Symbol(sym.INCREMENTO, createTokenInfo(yytext()));
          }
        case 147: break;
        case 18: 
          { return new Symbol(sym.PUNTO_Y_COMA, createTokenInfo(yytext()));
          }
        case 148: break;
        case 29: 
          { return new Symbol(sym.OR_LOGICO, createTokenInfo(yytext()));
          }
        case 149: break;
        case 27: 
          { /* DO NOTHING */
          }
        case 150: break;
        case 11: 
          { return new Symbol(sym.PARENTESIS_DER, createTokenInfo(yytext()));
          }
        case 151: break;
        case 16: 
          { return new Symbol(sym.LLAVE_IZQ, createTokenInfo(yytext()));
          }
        case 152: break;
        case 28: 
          { return new Symbol(sym.ASIGNACION_DIVISIVA, createTokenInfo(yytext()));
          }
        case 153: break;
        case 4: 
          { /* Ignorar espacios en blanco */
          }
        case 154: break;
        case 70: 
          { return new Symbol(sym.RETURN, createTokenInfo(yytext()));
          }
        case 155: break;
        case 61: 
          { return new Symbol(sym.GOTO, createTokenInfo(yytext()));
          }
        case 156: break;
        case 42: 
          { return new Symbol(sym.DESPLAZAMIENTO_IZQ, createTokenInfo(yytext()));
          }
        case 157: break;
        case 57: 
          { return new Symbol(sym.CASE, createTokenInfo(yytext()));
          }
        case 158: break;
        case 12: 
          { return new Symbol(sym.MULTIPLICACION, createTokenInfo(yytext()));
          }
        case 159: break;
        case 31: 
          { return new Symbol(sym.ASIGNACION_ADITIVA, createTokenInfo(yytext()));
          }
        case 160: break;
        case 44: 
          { return new Symbol(sym.ASIGNACION_MODULO, createTokenInfo(yytext()));
          }
        case 161: break;
        case 34: 
          { return new Symbol(sym.DO, createTokenInfo(yytext()));
          }
        case 162: break;
        case 69: 
          { return new Symbol(sym.SHORT, createTokenInfo(yytext()));
          }
        case 163: break;
        case 60: 
          { return new Symbol(sym.ELSE, createTokenInfo(yytext()));
          }
        case 164: break;
        case 63: 
          { return new Symbol(sym.NUM_CIENTIFICO, createTokenInfo(yytext()));
          }
        case 165: break;
        case 23: 
          { return new Symbol(sym.AND_BINARIO, createTokenInfo(yytext()));
          }
        case 166: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return new Symbol(sym.EOF, createTokenInfo(""));
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
