
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi;

<<<<<<< Updated upstream
=======
import java.util.HashMap;
import java.util.ArrayList;
>>>>>>> Stashed changes
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
<<<<<<< Updated upstream
    "\000\046\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\004\000\002\004\004" +
    "\000\002\004\007\000\002\004\011\000\002\004\007\000" +
    "\002\004\005\000\002\004\004\000\002\005\004\000\002" +
    "\005\006\000\002\006\003\000\002\006\003\000\002\006" +
    "\003\000\002\006\003\000\002\006\003\000\002\006\003" +
    "\000\002\006\003\000\002\006\003\000\002\006\003\000" +
    "\002\007\005\000\002\007\005\000\002\007\005\000\002" +
    "\007\005\000\002\007\005\000\002\007\005\000\002\007" +
    "\005\000\002\007\005\000\002\007\005\000\002\007\005" +
    "\000\002\007\004\000\002\007\004\000\002\007\005\000" +
    "\002\007\005\000\002\007\003\000\002\007\003" });
=======
    "\000\037\000\002\002\004\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\004\003\000\002\004\003" +
    "\000\002\004\004\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\007\000\002\011\005\000\002\012" +
    "\004\000\002\012\002\000\002\007\003\000\002\007\005" +
    "\000\002\007\004\000\002\007\003\000\002\007\004\000" +
    "\002\010\005\000\002\010\005\000\002\010\005\000\002" +
    "\010\005\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\005" });
>>>>>>> Stashed changes

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
<<<<<<< Updated upstream
    "\000\107\000\046\004\006\005\023\006\011\007\014\011" +
    "\033\012\015\013\010\014\013\016\024\030\004\032\026" +
    "\033\030\042\031\053\017\061\025\062\027\106\020\107" +
    "\021\001\002\000\004\106\uffec\001\002\000\030\044\036" +
    "\045\045\046\040\047\035\050\042\051\044\057\111\063" +
    "\041\064\046\065\043\066\037\001\002\000\004\106\ufff4" +
    "\001\002\000\004\057\110\001\002\000\004\053\104\001" +
    "\002\000\004\106\ufff2\001\002\000\004\106\101\001\002" +
    "\000\014\053\017\061\025\062\027\106\020\107\021\001" +
    "\002\000\004\106\uffef\001\002\000\004\053\071\001\002" +
    "\000\004\002\070\001\002\000\014\053\017\061\025\062" +
    "\027\106\020\107\021\001\002\000\034\044\uffdc\045\uffdc" +
    "\046\uffdc\047\uffdc\050\uffdc\051\uffdc\052\064\054\uffdc\057" +
    "\uffdc\063\uffdc\064\uffdc\065\uffdc\066\uffdc\001\002\000\032" +
    "\044\uffdd\045\uffdd\046\uffdd\047\uffdd\050\uffdd\051\uffdd\054" +
    "\uffdd\057\uffdd\063\uffdd\064\uffdd\065\uffdd\066\uffdd\001\002" +
    "\000\050\002\000\004\006\005\023\006\011\007\014\011" +
    "\033\012\015\013\010\014\013\016\024\030\004\032\026" +
    "\033\030\042\031\053\017\061\025\062\027\106\020\107" +
    "\021\001\002\000\004\106\ufff3\001\002\000\004\057\062" +
    "\001\002\000\014\053\017\061\025\062\027\106\020\107" +
    "\021\001\002\000\004\106\uffed\001\002\000\014\053\017" +
    "\061\025\062\027\106\020\107\021\001\002\000\004\106" +
    "\uffee\001\002\000\004\106\ufff0\001\002\000\050\002\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\011\ufffe\012\ufffe\013" +
    "\ufffe\014\ufffe\016\ufffe\030\ufffe\032\ufffe\033\ufffe\042\ufffe" +
    "\053\ufffe\061\ufffe\062\ufffe\106\ufffe\107\ufffe\001\002\000" +
    "\004\106\ufff1\001\002\000\032\044\036\045\045\046\040" +
    "\047\035\050\042\051\044\054\uffe0\057\uffe0\063\041\064" +
    "\046\065\043\066\037\001\002\000\014\053\017\061\025" +
    "\062\027\106\020\107\021\001\002\000\014\053\017\061" +
    "\025\062\027\106\020\107\021\001\002\000\014\053\017" +
    "\061\025\062\027\106\020\107\021\001\002\000\014\053" +
    "\017\061\025\062\027\106\020\107\021\001\002\000\014" +
    "\053\017\061\025\062\027\106\020\107\021\001\002\000" +
    "\014\053\017\061\025\062\027\106\020\107\021\001\002" +
    "\000\014\053\017\061\025\062\027\106\020\107\021\001" +
    "\002\000\014\053\017\061\025\062\027\106\020\107\021" +
    "\001\002\000\014\053\017\061\025\062\027\106\020\107" +
    "\021\001\002\000\014\053\017\061\025\062\027\106\020" +
    "\107\021\001\002\000\032\044\uffe2\045\uffe2\046\uffe2\047" +
    "\uffe2\050\uffe2\051\uffe2\054\uffe2\057\uffe2\063\uffe2\064\uffe2" +
    "\065\uffe2\066\uffe2\001\002\000\032\044\uffe6\045\uffe6\046" +
    "\uffe6\047\uffe6\050\uffe6\051\uffe6\054\uffe6\057\uffe6\063\uffe6" +
    "\064\uffe6\065\uffe6\066\uffe6\001\002\000\032\044\036\045" +
    "\045\046\uffe8\047\uffe8\050\uffe8\051\uffe8\054\uffe8\057\uffe8" +
    "\063\041\064\046\065\043\066\037\001\002\000\032\044" +
    "\uffe5\045\uffe5\046\uffe5\047\uffe5\050\uffe5\051\uffe5\054\uffe5" +
    "\057\uffe5\063\uffe5\064\uffe5\065\uffe5\066\uffe5\001\002\000" +
    "\032\044\036\045\045\046\uffe9\047\uffe9\050\uffe9\051\uffe9" +
    "\054\uffe9\057\uffe9\063\041\064\046\065\043\066\037\001" +
    "\002\000\032\044\uffe3\045\uffe3\046\uffe3\047\uffe3\050\uffe3" +
    "\051\uffe3\054\uffe3\057\uffe3\063\uffe3\064\uffe3\065\uffe3\066" +
    "\uffe3\001\002\000\032\044\036\045\045\046\uffeb\047\uffeb" +
    "\050\042\051\044\054\uffeb\057\uffeb\063\041\064\046\065" +
    "\043\066\037\001\002\000\032\044\uffe4\045\uffe4\046\uffe4" +
    "\047\uffe4\050\uffe4\051\uffe4\054\uffe4\057\uffe4\063\uffe4\064" +
    "\uffe4\065\uffe4\066\uffe4\001\002\000\032\044\uffe7\045\uffe7" +
    "\046\uffe7\047\uffe7\050\uffe7\051\uffe7\054\uffe7\057\uffe7\063" +
    "\uffe7\064\uffe7\065\uffe7\066\uffe7\001\002\000\032\044\036" +
    "\045\045\046\uffea\047\uffea\050\042\051\044\054\uffea\057" +
    "\uffea\063\041\064\046\065\043\066\037\001\002\000\032" +
    "\044\036\045\045\046\040\047\035\050\042\051\044\054" +
    "\uffe1\057\uffe1\063\041\064\046\065\043\066\037\001\002" +
    "\000\052\002\ufff7\004\ufff7\005\ufff7\006\ufff7\007\ufff7\011" +
    "\ufff7\012\ufff7\013\ufff7\014\ufff7\016\ufff7\023\ufff7\030\ufff7" +
    "\032\ufff7\033\ufff7\042\ufff7\053\ufff7\061\ufff7\062\ufff7\106" +
    "\ufff7\107\ufff7\001\002\000\050\002\uffff\004\uffff\005\uffff" +
    "\006\uffff\007\uffff\011\uffff\012\uffff\013\uffff\014\uffff\016" +
    "\uffff\030\uffff\032\uffff\033\uffff\042\uffff\053\uffff\061\uffff" +
    "\062\uffff\106\uffff\107\uffff\001\002\000\014\053\017\061" +
    "\025\062\027\106\020\107\021\001\002\000\032\044\036" +
    "\045\045\046\040\047\035\050\042\051\044\054\uffdf\057" +
    "\uffdf\063\041\064\046\065\043\066\037\001\002\000\030" +
    "\044\036\045\045\046\040\047\035\050\042\051\044\054" +
    "\067\063\041\064\046\065\043\066\037\001\002\000\032" +
    "\044\uffde\045\uffde\046\uffde\047\uffde\050\uffde\051\uffde\054" +
    "\uffde\057\uffde\063\uffde\064\uffde\065\uffde\066\uffde\001\002" +
    "\000\004\002\001\001\002\000\014\053\017\061\025\062" +
    "\027\106\020\107\021\001\002\000\030\044\036\045\045" +
    "\046\040\047\035\050\042\051\044\054\073\063\041\064" +
    "\046\065\043\066\037\001\002\000\046\004\006\005\023" +
    "\006\011\007\014\011\033\012\015\013\010\014\013\016" +
    "\024\030\004\032\026\033\030\042\031\053\017\061\025" +
    "\062\027\106\020\107\021\001\002\000\052\002\ufffb\004" +
    "\ufffb\005\ufffb\006\ufffb\007\ufffb\011\ufffb\012\ufffb\013\ufffb" +
    "\014\ufffb\016\ufffb\023\ufffb\030\ufffb\032\ufffb\033\ufffb\042" +
    "\ufffb\053\ufffb\061\ufffb\062\ufffb\106\ufffb\107\ufffb\001\002" +
    "\000\046\004\006\005\023\006\011\007\014\011\033\012" +
    "\015\013\010\014\013\016\024\030\004\032\026\033\030" +
    "\042\031\053\017\061\025\062\027\106\020\107\021\001" +
    "\002\000\052\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa" +
    "\011\ufffa\012\ufffa\013\ufffa\014\ufffa\016\ufffa\023\ufffa\030" +
    "\ufffa\032\ufffa\033\ufffa\042\ufffa\053\ufffa\061\ufffa\062\ufffa" +
    "\106\ufffa\107\ufffa\001\002\000\030\044\036\045\045\046" +
    "\040\047\035\050\042\051\044\057\100\063\041\064\046" +
    "\065\043\066\037\001\002\000\052\002\ufff8\004\ufff8\005" +
    "\ufff8\006\ufff8\007\ufff8\011\ufff8\012\ufff8\013\ufff8\014\ufff8" +
    "\016\ufff8\023\ufff8\030\ufff8\032\ufff8\033\ufff8\042\ufff8\053" +
    "\ufff8\061\ufff8\062\ufff8\106\ufff8\107\ufff8\001\002\000\006" +
    "\052\102\057\ufff6\001\002\000\014\053\017\061\025\062" +
    "\027\106\020\107\021\001\002\000\030\044\036\045\045" +
    "\046\040\047\035\050\042\051\044\057\ufff5\063\041\064" +
    "\046\065\043\066\037\001\002\000\014\053\017\061\025" +
    "\062\027\106\020\107\021\001\002\000\030\044\036\045" +
    "\045\046\040\047\035\050\042\051\044\054\106\063\041" +
    "\064\046\065\043\066\037\001\002\000\046\004\006\005" +
    "\023\006\011\007\014\011\033\012\015\013\010\014\013" +
    "\016\024\030\004\032\026\033\030\042\031\053\017\061" +
    "\025\062\027\106\020\107\021\001\002\000\052\002\ufff9" +
    "\004\ufff9\005\ufff9\006\ufff9\007\ufff9\011\ufff9\012\ufff9\013" +
    "\ufff9\014\ufff9\016\ufff9\023\ufff9\030\ufff9\032\ufff9\033\ufff9" +
    "\042\ufff9\053\ufff9\061\ufff9\062\ufff9\106\ufff9\107\ufff9\001" +
    "\002\000\052\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd" +
    "\011\ufffd\012\ufffd\013\ufffd\014\ufffd\016\ufffd\023\ufffd\030" +
    "\ufffd\032\ufffd\033\ufffd\042\ufffd\053\ufffd\061\ufffd\062\ufffd" +
    "\106\ufffd\107\ufffd\001\002\000\052\002\ufffc\004\ufffc\005" +
    "\ufffc\006\ufffc\007\ufffc\011\ufffc\012\ufffc\013\ufffc\014\ufffc" +
    "\016\ufffc\023\ufffc\030\ufffc\032\ufffc\033\ufffc\042\ufffc\053" +
    "\ufffc\061\ufffc\062\ufffc\106\ufffc\107\ufffc\001\002" });
=======
    "\000\067\000\016\003\ufffe\025\ufffe\026\ufffe\027\ufffe\030" +
    "\ufffe\037\ufffe\001\002\000\004\002\071\001\002\000\016" +
    "\003\012\025\006\026\015\027\016\030\010\037\013\001" +
    "\002\000\020\003\ufff7\004\067\025\ufff7\026\ufff7\027\ufff7" +
    "\030\ufff7\037\ufff7\001\002\000\016\003\uffff\025\uffff\026" +
    "\uffff\027\uffff\030\uffff\037\uffff\001\002\000\004\004\024" +
    "\001\002\000\016\003\ufffc\025\ufffc\026\ufffc\027\ufffc\030" +
    "\ufffc\037\ufffc\001\002\000\004\023\023\001\002\000\004" +
    "\002\000\001\002\000\016\003\ufffd\025\ufffd\026\ufffd\027" +
    "\ufffd\030\ufffd\037\ufffd\001\002\000\020\003\ufff6\004\021" +
    "\025\ufff6\026\ufff6\027\ufff6\030\ufff6\037\ufff6\001\002\000" +
    "\020\003\ufff5\004\017\025\ufff5\026\ufff5\027\ufff5\030\ufff5" +
    "\037\ufff5\001\002\000\004\023\020\001\002\000\036\003" +
    "\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8\017\ufff8\021\ufff8" +
    "\022\ufff8\025\ufff8\026\ufff8\027\ufff8\030\ufff8\035\ufff8\037" +
    "\ufff8\001\002\000\004\023\022\001\002\000\036\003\ufff9" +
    "\004\ufff9\005\ufff9\006\ufff9\007\ufff9\017\ufff9\021\ufff9\022" +
    "\ufff9\025\ufff9\026\ufff9\027\ufff9\030\ufff9\035\ufff9\037\ufff9" +
    "\001\002\000\016\003\ufffb\025\ufffb\026\ufffb\027\ufffb\030" +
    "\ufffb\037\ufffb\001\002\000\004\017\025\001\002\000\004" +
    "\020\026\001\002\000\004\021\027\001\002\000\032\003" +
    "\ufff1\004\ufff1\005\ufff1\006\ufff1\007\ufff1\017\ufff1\021\ufff1" +
    "\022\ufff1\025\ufff1\026\ufff1\027\ufff1\035\ufff1\001\002\000" +
    "\016\003\ufff4\025\ufff4\026\ufff4\027\ufff4\030\ufff4\037\ufff4" +
    "\001\002\000\032\003\042\004\040\005\032\006\044\007" +
    "\037\017\035\021\027\022\034\025\033\026\050\027\047" +
    "\035\045\001\002\000\016\012\uffe6\013\uffe6\014\uffe6\015" +
    "\uffe6\020\uffe6\023\uffe6\001\002\000\004\004\067\001\002" +
    "\000\036\003\ufff3\004\ufff3\005\ufff3\006\ufff3\007\ufff3\017" +
    "\ufff3\021\ufff3\022\ufff3\025\ufff3\026\ufff3\027\ufff3\030\ufff3" +
    "\035\ufff3\037\ufff3\001\002\000\014\004\040\005\032\006" +
    "\044\007\037\017\035\001\002\000\032\003\uffed\004\uffed" +
    "\005\uffed\006\uffed\007\uffed\017\uffed\021\uffed\022\uffed\025" +
    "\uffed\026\uffed\027\uffed\035\uffed\001\002\000\016\012\uffe4" +
    "\013\uffe4\014\uffe4\015\uffe4\020\uffe4\023\uffe4\001\002\000" +
    "\016\012\uffe7\013\uffe7\014\uffe7\015\uffe7\020\uffe7\023\uffe7" +
    "\001\002\000\032\003\ufff2\004\ufff2\005\ufff2\006\ufff2\007" +
    "\ufff2\017\ufff2\021\ufff2\022\ufff2\025\ufff2\026\ufff2\027\ufff2" +
    "\035\ufff2\001\002\000\004\023\064\001\002\000\014\012" +
    "\054\013\052\014\053\015\055\023\063\001\002\000\016" +
    "\012\uffe5\013\uffe5\014\uffe5\015\uffe5\020\uffe5\023\uffe5\001" +
    "\002\000\014\004\040\005\032\006\044\007\037\017\035" +
    "\001\002\000\032\003\ufff0\004\ufff0\005\ufff0\006\ufff0\007" +
    "\ufff0\017\ufff0\021\ufff0\022\ufff0\025\ufff0\026\ufff0\027\ufff0" +
    "\035\ufff0\001\002\000\004\004\017\001\002\000\004\004" +
    "\021\001\002\000\014\012\054\013\052\014\053\015\055" +
    "\023\056\001\002\000\014\004\040\005\032\006\044\007" +
    "\037\017\035\001\002\000\014\004\040\005\032\006\044" +
    "\007\037\017\035\001\002\000\014\004\040\005\032\006" +
    "\044\007\037\017\035\001\002\000\014\004\040\005\032" +
    "\006\044\007\037\017\035\001\002\000\032\003\uffef\004" +
    "\uffef\005\uffef\006\uffef\007\uffef\017\uffef\021\uffef\022\uffef" +
    "\025\uffef\026\uffef\027\uffef\035\uffef\001\002\000\016\012" +
    "\uffe8\013\uffe8\014\uffe8\015\uffe8\020\uffe8\023\uffe8\001\002" +
    "\000\016\012\uffeb\013\uffeb\014\053\015\055\020\uffeb\023" +
    "\uffeb\001\002\000\016\012\uffe9\013\uffe9\014\uffe9\015\uffe9" +
    "\020\uffe9\023\uffe9\001\002\000\016\012\uffea\013\uffea\014" +
    "\053\015\055\020\uffea\023\uffea\001\002\000\032\003\uffee" +
    "\004\uffee\005\uffee\006\uffee\007\uffee\017\uffee\021\uffee\022" +
    "\uffee\025\uffee\026\uffee\027\uffee\035\uffee\001\002\000\032" +
    "\003\uffec\004\uffec\005\uffec\006\uffec\007\uffec\017\uffec\021" +
    "\uffec\022\uffec\025\uffec\026\uffec\027\uffec\035\uffec\001\002" +
    "\000\014\012\054\013\052\014\053\015\055\020\066\001" +
    "\002\000\016\012\uffe3\013\uffe3\014\uffe3\015\uffe3\020\uffe3" +
    "\023\uffe3\001\002\000\004\023\070\001\002\000\036\003" +
    "\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\017\ufffa\021\ufffa" +
    "\022\ufffa\025\ufffa\026\ufffa\027\ufffa\030\ufffa\035\ufffa\037" +
    "\ufffa\001\002\000\004\002\001\001\002" });
>>>>>>> Stashed changes

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
<<<<<<< Updated upstream
    "\000\107\000\016\002\015\003\021\004\031\005\006\006" +
    "\011\007\004\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\076\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\065\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\004\062\005\006\006\011\007\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\060\001\001" +
    "\000\002\001\001\000\004\007\033\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\057\001\001\000\004\007" +
    "\056\001\001\000\004\007\055\001\001\000\004\007\054" +
    "\001\001\000\004\007\053\001\001\000\004\007\052\001" +
    "\001\000\004\007\051\001\001\000\004\007\050\001\001" +
    "\000\004\007\047\001\001\000\004\007\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\071\001" +
    "\001\000\002\001\001\000\012\004\073\005\006\006\011" +
    "\007\004\001\001\000\002\001\001\000\012\004\075\005" +
    "\006\006\011\007\004\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\102\001\001\000\002\001\001\000\004\007\104\001\001" +
    "\000\002\001\001\000\012\004\106\005\006\006\011\007" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });
=======
    "\000\067\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\010\004\006\005\010\006\013\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\027\001\001\000\004\012\030\001\001\000\002\001\001" +
    "\000\012\006\045\007\040\010\042\011\035\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\064\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\050\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\061\001\001\000\004\010\060\001" +
    "\001\000\004\010\057\001\001\000\004\010\056\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });
>>>>>>> Stashed changes

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



<<<<<<< Updated upstream
    public void report_error(String message, Object info) {
        if (info instanceof Symbol) {
            Symbol symbol = (Symbol) info;
            System.err.println("Error de sintaxis en línea " + symbol.left + ", columna " + symbol.right + ": " + message);
        } else {
            System.err.println("Error de sintaxis: " + message);
        }
    }

    public void syntax_error(Symbol cur_token) {
        System.err.println("Error de sintaxis en línea " + cur_token.left + ", columna " + cur_token.right + ": token inesperado '" + cur_token.value + "'");
=======
    public ArrayList<String> syntaxErrors = new ArrayList<>();
    public ArrayList<String> semanticErrors = new ArrayList<>();

    private HashMap<String, String> symbolTable = new HashMap<>();

    private void declareVariable(String id, String type) {
        if (symbolTable.containsKey(id)) {
            semanticErrors.add("Error: Variable '" + id + "' ya ha sido declarada.");
        } else {
            symbolTable.put(id, type);
        }
    }

    private void checkVariable(String id) {
        if (!symbolTable.containsKey(id)) {
            semanticErrors.add("Error: Variable '" + id + "' no ha sido declarada.");
        }
    }

    public ArrayList<String> getSyntaxErrors() {
        return syntaxErrors;
    }

    public ArrayList<String> getSemanticErrors() {
        return semanticErrors;
>>>>>>> Stashed changes
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 1: // program ::= stmt_list 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 1: // program ::= declaration_list END 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 2: // stmt_list ::= stmt_list stmt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 2: // declaration_list ::= declaration_list declaration 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 3: // stmt_list ::= stmt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 3: // declaration_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 4: // stmt ::= decl PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 4: // declaration ::= var_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 5: // stmt ::= expr PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 5: // declaration ::= func_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 6: // stmt ::= IF PARENTESIS_IZQ expr PARENTESIS_DER stmt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 6: // declaration ::= error PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 syntaxErrors.add("Error en declaración."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 7: // stmt ::= IF PARENTESIS_IZQ expr PARENTESIS_DER stmt ELSE stmt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 7: // var_decl ::= INT ID PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 declareVariable("id", "int"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decl",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 8: // stmt ::= WHILE PARENTESIS_IZQ expr PARENTESIS_DER stmt 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 8: // var_decl ::= FLOAT ID PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 declareVariable("id", "float"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decl",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 9: // stmt ::= RETURN expr PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 9: // var_decl ::= CHAR ID PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 declareVariable("id", "char"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_decl",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 10: // stmt ::= BREAK PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 10: // func_decl ::= INT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_decl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 11: // decl ::= type ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 11: // func_decl ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_decl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 12: // decl ::= type ID ASIGNACION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 12: // func_decl ::= CHAR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_decl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 13: // type ::= INT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 13: // func_decl ::= VOID ID PARENTESIS_IZQ PARENTESIS_DER block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("func_decl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 14: // type ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 14: // block ::= LLAVE_IZQ statement_list LLAVE_DER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("block",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 15: // type ::= CHAR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 15: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 16: // type ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 16: // statement_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 17: // type ::= VOID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 17: // statement ::= var_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 18: // type ::= UNSIGNED 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // type ::= SIGNED 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 18: // statement ::= RETURN expr PUNTO_Y_COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // statement ::= expr PUNTO_Y_COMA 
            {
              Object RESULT =null;

<<<<<<< Updated upstream
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 21: // type ::= LONG 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 20: // statement ::= block 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 22: // expr ::= expr ADITIVO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 21: // statement ::= error PUNTO_Y_COMA 
            {
              Object RESULT =null;
		 syntaxErrors.add("Error en sentencia."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 23: // expr ::= expr SUSTRACTIVO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 22: // expr ::= expr ADITIVO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 24: // expr ::= expr MULTIPLICACION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 23: // expr ::= expr SUSTRACTIVO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 25: // expr ::= expr DIVISION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 24: // expr ::= expr MULTIPLICACION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 26: // expr ::= expr IGUALDAD expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 25: // expr ::= expr DIVISION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 27: // expr ::= expr NO_IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 26: // expr ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 28: // expr ::= expr MAYOR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 27: // expr ::= NUM 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 29: // expr ::= expr MENOR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 28: // expr ::= CHAR_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 30: // expr ::= expr MAYOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 29: // expr ::= STRING 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
<<<<<<< Updated upstream
          case 31: // expr ::= expr MENOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= INCREMENTO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= DECREMENTO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= ID ASIGNACION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= PARENTESIS_IZQ expr PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= NUM 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
=======
          case 30: // expr ::= PARENTESIS_IZQ expr PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
>>>>>>> Stashed changes
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
