package com.compi;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  // Palabras reservadas
  public static final int INT = 0;
  public static final int FLOAT = 1;
  public static final int CHAR = 2;
  public static final int UNSIGNED = 3;
  public static final int CONST = 4;
  public static final int DOUBLE = 5;
  public static final int IF = 6;
  public static final int WHILE = 7;
  public static final int RETURN = 8;
  public static final int AUTO = 9;
  public static final int BREAK = 10;
  public static final int CASE = 11;
  public static final int CONTINUE = 12;
  public static final int DEFAULT = 13;
  public static final int DO = 14;
  public static final int ELSE = 15;
  public static final int ENUM = 16;
  public static final int EXTERN = 17;
  public static final int FOR = 18;
  public static final int GOTO = 19;
  public static final int LONG = 20;
  public static final int REGISTER = 21;
  public static final int SHORT = 22;
  public static final int SIGNED = 23;
  public static final int SIZEOF = 24;
  public static final int STATIC = 25;
  public static final int STRUCT = 26;
  public static final int SWITCH = 27;
  public static final int TYPEDEF = 28;
  public static final int UNION = 29;
  public static final int VOID = 30;
  public static final int VOLATILE = 31;

  // Operadores y delimitadores
  public static final int IGUALDAD = 32;
  public static final int NO_IGUAL = 33;
  public static final int ADITIVO = 34;
  public static final int SUSTRACTIVO = 35;
  public static final int MULTIPLICACION = 36;
  public static final int DIVISION = 37;
  public static final int ASIGNACION = 38;
  public static final int PARENTESIS_IZQ = 39;
  public static final int PARENTESIS_DER = 40;
  public static final int LLAVE_IZQ = 41;
  public static final int LLAVE_DER = 42;
  public static final int PUNTO_Y_COMA = 43;
  public static final int COMA = 44;
  public static final int INCREMENTO = 45;
  public static final int DECREMENTO = 46;
  public static final int MAYOR_IGUAL = 47;
  public static final int MENOR_IGUAL = 48;
  public static final int MAYOR = 49;
  public static final int MENOR = 50;
  public static final int AND_BINARIO = 51;
  public static final int OR_BINARIO = 52;
  public static final int XOR_BINARIO = 53;
  public static final int MODULO = 54;
  public static final int DESPLAZAMIENTO_IZQ = 55;
  public static final int DESPLAZAMIENTO_DER = 56;
  public static final int ASIGNACION_ADITIVA = 57;
  public static final int ASIGNACION_SUSTRACTIVA = 58;
  public static final int ASIGNACION_MULTIPLICATIVA = 59;
  public static final int ASIGNACION_DIVISIVA = 60;
  public static final int ASIGNACION_MODULO = 61;
  public static final int AND_LOGICO = 62;
  public static final int OR_LOGICO = 63;
  public static final int NOT_LOGICO = 64;
  public static final int COMPLEMENTO_BINARIO = 65;

  // Otros
  public static final int ID = 66;
  public static final int NUM = 67;
  public static final int NUM_HEX = 68;
  public static final int NUM_OCT = 69;
  public static final int STRING = 70;
  public static final int CHAR_LITERAL = 71;
  public static final int EOF = 72;
  public static final int NEWLINE = 73;
  public static final int ERROR = 74;
  public static final int NUM_CIENTIFICO = 75;
}
